### ISSUE TITLE
Failed to stage block

### ISSUE THREAD

**Issue by gunar** [nelsonjchen/gargantuan-takeout-rocket#5] opened 2022-09-20 17:31 UTC
GTR worked for me last month but this month it's not working. Wondering if you might have a clue as to what might be happening.

```
Failed to stage block: 400 <?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format. RequestId:a853c6ce-301e-00a1-1016-cd4c1b000000 Time:2022-09-20T17:29:47.7956447Z</Message><HeaderName>x-ms-copy-source</HeaderName><HeaderValue>```

**Comment by gunar** [comment] 2022-09-20 17:34
It seems the service worker was inactive. Clicking to see the logs activated it. I've also refreshed the Takeout page and attempted to download one of the packages.

I don't know exactly what changed but it worked.

**Comment by gunar** [comment] 2022-09-20 17:38
Happened again on the 3rd file, after 2 successful ones.

**Comment by gunar** [comment] 2022-09-20 17:47
Refreshing the page after every file seems to help but doesn't solve it. Still getting intermittent errors.

For future reference, this is what the CloudFlare Worker dashboard looks like:

![image](https://user-images.githubusercontent.com/7684574/191328248-cb30459a-d962-4eba-b9e8-28dc4463dd04.png)

**Comment by nelsonjchen** [comment] 2022-09-20 17:55
Hmm, not sure what's going on here. My random cursory guess, since nothing major has changed on this toolkit, would be that Azure may have rolled out an expectation for a filename in the URL copy source? Or some other crazy validation? The base64'd URL is supposed to be as benign as it gets for not causing problems.

**Comment by nelsonjchen** [comment] 2022-09-21 02:17
fwiw, good news, I can repro.

**Comment by nelsonjchen** [comment] 2022-09-21 02:23
It's not consistent either. Retrying works. I think I might just make the extension consider this a retry-able event.

**Comment by nelsonjchen** [comment] 2022-09-21 02:30
> Hmm, not sure what's going on here. My random cursory guess, since nothing major has changed on this toolkit, would be that Azure may have rolled out an expectation for a filename in the URL copy source? Or some other crazy validation? The base64'd URL is supposed to be as benign as it gets for not causing problems.

Also, this technically breaks an API contract, if it wasn't a bug. They have a versioning system after all:

https://learn.microsoft.com/en-us/rest/api/storageservices/versioning-for-the-azure-storage-services

I believe this to be a bug on Azure's side. I'll make the extension retry on 400s errors from this though.

**Comment by nelsonjchen** [comment] 2022-09-21 03:30
Yeah, I don't know why this is happening. Let's check back in a week or two. I'm like semi-certain this bug would break some VIP's very important workflow. Even with making the extension retry on 400s, it does not help, as the same URL causes Azure to reject it. I've reverted the retrying on 400s for now. 

In the meantime, here's an expired URL that causes 400s that one could look at that I've pasted here for reference. It's very plain and should be non-offensive but for whatever reason, it definitely pisses off Azure. Since we control the proxy, maybe we can another layer of optional shift of the base64 in case there's some bad Azure heuristic flipping off. 

https://gtr-proxy.677472.xyz/p/aHR0cHM6Ly8wMGY3NGJhNDRiNDM0NzM4ZDg5ZTk5OTcyOWJlNzJjYjEzZmRjZjA5MjctYXBpZGF0YS5nb29nbGV1c2VyY29udGVudC5jb20vZG93bmxvYWQvc3RvcmFnZS92MS9iL2RhdGFsaWJlcmF0aW9uL28vMjAyMjA5MjBUMTc1OTAwWiUyRi00MzExNjkzNzE3NzE2MDEyNTQ1JTJGNTJlYzRkODQtNTE2MC00ZTFjLWFiYTItM2NiNGM1MDRmNGVmJTJGMSUyRmYwYWRlODdiLWM1Y2QtNDdjMi1iNzIxLTJmOTYxYjBjNDg2ND9qaz1BRnNoRTNXeTU4Y0JpS2t4MDdXWldzUXd0dS1QMHpzclgzX1dBM0NtZV9seXN2bTZIZXNHOGNrMVlUTDg3eUt2b2ZIekZZNjN6N3lwRzJtclotRnJpa1ZwclBDY1BkNHpPemxBaGxQaWI5UGxfWTM3UTBOTVJxRDllRGdCQ3MtNmYyeFBsWU5ia0daX0RIUUtKV3N2LWNReEhxampnQk5GTG5pVGFqV2FMYXhRaS1ZQ0dZTUxUUl9FLTk5N0RnTmlBTlJnZVFBZnlqWVFsa3JFRDNCZjFJa1VVMnFhXzdFa3dSNEJrWDFCN0Q5NkpyQ1B4MF9zemFpeE5qVmgwXzhIdndXa2U0cmtIRmhpckRqY0N4eEZZS0dkTUtmSC1zaFBNYVdIdjVZcXhRN3IwMXZxanBuVFBRWmZkY2FvbGR1TE51anVFZF9vRElGc3NXakc5Y1hKc1JQb0VSaEhlRF95dnIza3pmQmhRUmlDb3M2ZF9xY0J4NTlaOTRiOC1aTVFJcERvS1BlbjJxekdEdThpSzZMSWI0M2xRdVloS09XZnNHdFBiWVMzcVd4UmhheVR2VW5Vb1d5X0h6UW53eHFEOENsUWhscEl6ODdFUk0xZ0NQT0FodkhMeFNMUDJENW1nZzZsQ1kzamJPZUZodGd2UjM3N3VpaXlZZmtib0hYeGh1WVVxTTRISXpwQkwzdjF3Zzl5cU1KQmpIeHJZSFlEc3Uxc3I1TnliUDhPS20ydnN6dEJOT2N4VFExa3VXcXFRWWVLaG5zSGREMG53TlVMOVBGSkhJQVVxZUdsaXRXNUpnc2ZEZUpmczNtVEFJdXNzRGNEYXcyWndsQVVfdlVqSHF2T19NU09zb3lZRWFnZnlXOXFwRzY2RnNmbWZiZ0FOT3lzWGJpVllFWTgyeXNaRl96cTFQMlN2eWlxSFdHbWNNNmU4YVRPeDZsdFJKbUxvR1JCcThDdzcwYmphRks4TFVMUnNLX3ppaFRuNFFNNzBJMkJlN2tUT1pmOGdMOEZ4MVZuSlNFOUVjek9QSTFnYmRIM0NFVWxOeW5MR0tBRjZuSFc3X2lxdTU4dHdnaE5hYjh6OUxFcm9aUnhFcUl1UTlRTFp4NFdaM3ZYZ1M1NGxPODQ1ZU9mbE5pYTBCejlvdldqdnRGVnZiY0NEdlctbzJmVkpWeHdXTHowQXRCcDhMeklOMjhvRWxDQlRmRXY3RGdsNjEtNXdJMzJWaXVKMDQzUGR1NnRqb2taVWpCT0VlQUNYT2JKNWdfRzFRUGgxbDU3MGlVd3B3VkVLOXRkRzM1QUM4VVI1Snd1SDdTbVF1Ul9WZi1yZXRRRXN6VXJZcUNsWEd5ay1TRzk3MEx3RFJRdkFWVEZjck1XQmczOFBvbWtLZHcxUlFxS283ZFpFNEhDXzQ1bzZOaWh0ak05T01tVmUxVmhpNi1TUk1aTk9US0t4UGotNHp6SHlwNlNBZ0w1V2VzNUVlRGZneTh5eEhYZGtqZ3JaOU1VYzJPRXA4Uk1BMEdDcy1hSTY3d2xBZVk5aFpGZnVIcTF0S3J3cjJSSEdkVUQtb29JQTNPN0Rac3djaGpVempJV1BlajlaUHhaQzdfeG1HQTNEQXZFVkhKTFlodDhtQzA2cV9kZ3cxcnBYczE5dU1QLXBPOWNGRzFxSTlsaGU3Slpfa2h1b0NUVXltYjliaVNHNW1SOV94SkxKbEhGdkd0OFhOaThtNWZ6VEt0MU8tR29mS2N1R2phQ1BpcjM4SDlxMDAzN1FLWXV4WDBWQjBlVnJRNHlOVE4xaWpHcnBTTUxQcTAmaXNjYT0x

**Comment by nelsonjchen** [comment] 2022-09-21 03:35
I do have a server at https://github.com/nelsonjchen/put-block-from-url-esc-issue-demo-server so maybe I'll try to recreate this issue and report it. I might still get crickets though like with my URL escaping issue. I can see why an org might be hesitant to change their `/` handling as it could break past "working" customers, but that base64 url is as plain as it can get.

**Comment by nelsonjchen** [comment] 2022-10-10 00:04
Well, waiting it out certainly didn't help. I guess no one (with money!) has raised the issue to Microsoft.

I still see this issue. I'm on vacation for the next two weeks. My own periodic takeout is currently interrupted by this. I'll look at it when I get back.

I'll see if this is something that can be reproduced outside of Takeout, if there's any rhyme or reason, and raise it up. 

Alternatively, I think I might also see if there's a way to teach workers itself to do the transloading and skip having extra hops. If CF doesn't charge, that would pave the way to S3 as a target too. Can Workers itself do the transloading without charging for time it is facilitating a transloading?

**Comment by nelsonjchen** [comment] 2022-10-24 05:05
Looked at this today. Still sketching out new implementation. One thing for sure, the extension will still be the "driver" to copy blocks over. Workers only support 6 connections per request at most. We'll still need the browser extension to toss out many simultaneous connections to speed things up.

I also haven't looked at the proxy for months and will need to revisit how to develop workers. For now, the typescript doesn't complain and it does seem like the fetch from remote could be tossed into a put. I also wanted to see if I could eliminate a homegrown Azure Blob storage client, but I got scared of the mega huge library and it didn't seem to expose the necessary low level API anyway. 

Still sketching out the proxy too. I'm thinking of making the API for my own block staging just aping what I need from Microsoft's.

**Comment by nelsonjchen** [comment] 2022-10-30 02:00
I had functionality in the proxy to allow any amount of characters after the end of the base64 to "fool" azcopy into having a filename to save to. I've modified the extension to just stick on a fake filename at the end and kicked off another full Google Takeout backup. Here's to hoping that would work as a workaround. Didn't put more work into the rearchitecting though.

**Comment by nelsonjchen** [comment] 2022-10-31 07:16
For whatever reason, the URLs after base-64'ication are now ~2143 bytes. They need to be less than 2048 afterwards.

https://learn.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url#:~:text=Required.%20Specifies%20the%20URL,of%20source%20object%20URLs%3A

I don't know if the limit was always there or ~100 bytes has been added since.

**Comment by nelsonjchen** [comment] 2022-11-27 22:48
Initial unit tests working on new architecture

```mermaid
graph LR
  A[Google Takeout]--3. Download Data .-> B[Cloudflare Worker]
  B --2. Fetch .-> A
  B --4. Push.-> C[Azure Storage]
  Browser -- 1. Control CF Worker / Azure Storage Signed SAS.-> B
```

https://github.com/nelsonjchen/gtr-proxy/pull/8  

Though, _integration_ test on real cloudflare from extension unit tests not working. Looking into it. I guess I need more data for blocks or something or whitelisting of headers or whatever.

**Comment by rolltidehero** [comment] 2022-12-30 19:26
dang! i suggest using rclone until this is resolved. I really love this tool and hope it's figured out soon. sadly, I am not skilled in this particular programming language.

**Comment by nelsonjchen** [comment] 2023-01-15 10:07
Continuing to work on this. Got a very static integration test going on the proxy that works for transloading. Hash match!

Definitely have bugs in the extension that I'm working on and the tests in there against the proxy hosted on Cloudflare are not working. Planner seems to be off by some KB/bytes somehow. Hashes don't match

✊off by ones you sob plague problem in programming!!

Also, unfortunately, the upper chunk limit size is 100MB from 500MB before. Outgoing fetch connections in the Cloudflare Workers runtime are proxied by a Cloudflare server and the 100MB post size limit applies. Will need to see what happens when I try it with a real 50GB ZIP archive. This was not an issue with Azure pulling as that's unlimited in general. We'll see. Scaling reveals things. 

Also, the new architecture should also allow for future destinations such as R2 with an S3 API. Now I wouldn't *store* stuff there, but it's a great staging area that will be compatible with download managers for downloading to a local physical backup and should be relatively low-cost during staging.

**Comment by nelsonjchen** [comment] 2023-01-15 18:01
Hmm, need to figure out batching. Cloudflare has a global limit of 600 requests per minute per IP. This would constrain the backup speed to ~50GB/min/IP with this approach. 

https://community.cloudflare.com/t/workers-rate-limit-429/303959/2

**Comment by nelsonjchen** [comment] 2023-01-17 04:47
Ugh, I'm hitting Azure limits. Apparently they have an *ingress* limit! this did not exist with put block from url. 😞 

https://www.bluematador.com/docs/troubleshooting/azure-storage-account-limit#:~:text=The%20ingress%20limit%20restricts%20the,on%20region%20and%20replication%20configuration.

```
<?xml version="1.0" encoding="utf-8"?><Error><Code>ServerBusy</Code><Message>Ingress is over the account limit.
RequestId:0fb7762d-301e-00e7-562d-2af58e000000
Time:2023-01-17T04:41:26.3315849Z</Message></Error>
```

Wild! 

This is 5Gbps or 600MB/s. Darn, I did not think there was an ingress limit at all.

**Comment by nelsonjchen** [comment] 2023-01-17 04:58
So here's my new plan for now. I'm going to keep this new path, but instead of targeting Azure since it's not fast enough to take meaty direct PUTs, I'll re-jigger it for S3 APIs such as Cloudflare R2 and AWS S3 in the future. 

R2 is great for staging a local backup while your download manager works to download it to you physically. They just don't have lifecycles rule for the moment, so a screwup and forgetting to delete can be costly. 

AWS S3 has a competitive deep archival option too. It also does not have any ingress limit like Azure from what I can see. 

In the meantime, I'll see if I can repair the original architecture. I only base64'd the URL because the %2Fs were getting erroneously fixed by Azure. I think it should be OK to just armor the %2Fs somehow and that should get me back down below the 2KB URL limit without base64'ing.

**Comment by nelsonjchen** [comment] 2023-02-06 08:09
I've taken out the base64 stuff and just replaced it with just armoring the `%2F`s to `%252F` and undoing that in CF. 

![image](https://user-images.githubusercontent.com/5363/216918106-8e9839ea-0be5-4c83-ada7-3dc974fe808e.png)

I was able to transload 50GB from Google to Azure with this. 

I'll probably work through the week in my spare time to get this new release out. :)

**Comment by nelsonjchen** [comment] 2023-02-10 07:23
It's been four days since I've requested a really full takeout of all my Google stuff. I haven't forgotten!

Will go through my guide by hand again and make sure the steps all still work. 

Super stoked to be closing this when the takeout is available and all that's left is for me to do the transload, **fast**.

**Comment by nelsonjchen** [comment] 2023-02-11 18:09
My takeout failed, probably because I checked the Access log option that was defaultly unchecked but had massive warnings saying it takes forever. Restarted takeout request now without that option.

**Closed as completed** 2023-02-18 00:15 UTC

**Comment by nelsonjchen** [comment] 2023-02-18 00:21
Fixed! You will need to redeploy a new GTR Proxy worker and update your extension as well.
